Region: 
Image:
  Os: alinux2
HeadNode:
  InstanceType: 
  Networking:
    SubnetId: 
  Ssh:
    KeyName: 
  Dcv:
    Enabled: true  
  Iam:
    S3Access:
      - EnableWriteAccess: true
        BucketName: '*'
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore      
  CustomActions:
    OnNodeStart:
      Script: s3://tempbucket/bootstrap-scripts/pcluster-on-node-start.sh        
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    CapacityType: SPOT
    ComputeResources:
    - Name: t2micro
      InstanceType: 
      MinCount: 
      MaxCount:
      DisableSimultaneousMultithreading:
      Efa:
        Enabled:
    Networking:
      PlacementGroup:
        Enabled:
      SubnetIds:
      - 
    Iam:
      S3Access:
        - EnableWriteAccess: true
          BucketName: '*'
