AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the ImageBuilder component, recipe, infra configuration, distribution configuration, and pipeline for Nextflow Advanced for Research Gateway
Parameters:
  SourceBucketName:
    Type: String
  VPCId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetId:
    Type: AWS::EC2::Subnet::Id
  MasterAMI:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  Ver:
    Type: String
    Default: "1.0.0"

Resources:
  #############
  # COMPONENTS
  #############
  ComponentConfigureOS:
    Type: "AWS::ImageBuilder::Component"
    Properties:
      Name: !Sub "${AWS::StackName}-ConfigureOSComponent"
      Platform: "Linux"
      Version: !Ref Ver
      Description: "Configure Operating System Patches"
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "ConfigureOS"]]
        ResourceType: "RLCatalyst-Research-Gateway"
      Data: |
        name: ConfigureOS
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: UpdateOS
                action: UpdateOS
  ComponentNextflowAdvanced:
    Type: "AWS::ImageBuilder::Component"
    Properties:
      Name: !Sub "${AWS::StackName}-ComponentNextflow_Advanced"
      Platform: "Linux"
      Version: !Ref Ver
      Description: "Configure Nextflow_Advanced Server"
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "ConfigureNextflow_Advanced"]]
        ResourceType: "RLCatalyst-Research-Gateway"
      Data: !Sub |
        name: Nextflow-Provisioner
        description: This is the provisioner for Nextflow-Advanced for Research Gateway
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: AddFiles
                action: S3Download
                inputs:
                - source: s3://${SourceBucketName}/nextflow-advanced.tar.gz
                  destination: /tmp/nextflow-advanced.tar.gz
              - name: ExtractFiles
                action: ExecuteBash
                inputs:
                  commands:
                    - tar -xvf /tmp/nextflow-advanced.tar.gz
                    - mkdir -p /tmp/nextflow
                    - cp /tmp/Nextflow-Advanced/machine-images/config/infra/files/nextflow/* /tmp/nextflow
                    - bash /tmp/Nextflow-Advanced/machine-images/config/infra/provisioners/provision-nextflow.sh
  ComponentRStudio:
    Type: "AWS::ImageBuilder::Component"
    Properties:
      Name: !Sub "${AWS::StackName}-ComponentRStudio"
      Platform: "Linux"
      Version: !Ref Ver
      Description: "Configure RStudio Server"
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "ConfigureRStudio"]]
        ResourceType: "RLCatalyst-Research-Gateway"
      Data: !Sub |
        name: RStudio-Provisioner
        description: This is the provisioner for RStudio for Research Gateway
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: AddFiles
                action: S3Download
                inputs:
                - source: "s3://${SourceBucketName}/rstudio.tar.gz"
                  destination: /tmp/rstudio.tar.gz
              - name: ExtractFiles
                action: ExecuteBash
                inputs:
                  commands:
                    - tar -xvf /tmp/rstudio.tar.gz 
                    - mkdir -p /tmp/rstudio
                    - cp /tmp/RStudio/machine-images/config/infra/files/rstudio/* /tmp/rstudio
                    - bash /tmp/RStudio/machine-images/config/infra/provisioners/provision-rstudio.sh
  ComponentPCluster:
    Type: "AWS::ImageBuilder::Component"
    Properties:
      Name: !Sub "${AWS::StackName}-ComponentPCluster"
      Platform: "Linux"
      Version: !Ref Ver
      Description: "Configure PCluster Server"
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "ConfigurePCluster"]]
        ResourceType: "RLCatalyst-Research-Gateway"
      Data: !Sub |
        name: PCluster-Provisioner
        description: This is the provisioner for PCluster for Research Gateway
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: AddFiles
                action: S3Download
                inputs:
                - source: "s3://${SourceBucketName}/PCluster.tar.gz"
                  destination: /tmp/PCluster.tar.gz
              - name: ExtractFiles
                action: ExecuteBash
                inputs:
                  commands:
                    - tar -xvzf /tmp/PCluster.tar.gz -C /tmp
                    - mkdir -p /tmp/cluster
                    - cp /tmp/PCluster/machine-images/config/infra/files/pcluster/* /tmp/cluster
                    - bash /tmp/PCluster/machine-images/config/infra/provisioners/provision-launch.sh

  #############
  # RECIPE
  #############
  RStudioImageRecipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Sub "${AWS::StackName}-RStudioImageRecipe"
      Version: !Ref Ver
      ParentImage: !Ref MasterAMI
      Description: !Sub "${AWS::StackName}-RStudioImageRecipe"
      Components:
        - ComponentArn: !GetAtt ComponentConfigureOS.Arn
        - ComponentArn: !GetAtt ComponentRStudio.Arn
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "RStudioImageRecipe"]]
        ResourceType: "RLCatalyst-Research-Gateway"

  NextflowAdvancedImageRecipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Sub "${AWS::StackName}-Nextflow_AdvancedImageRecipe"
      Version: !Ref Ver
      ParentImage: !Ref MasterAMI
      Description: !Sub "${AWS::StackName}-Nextflow_AdvancedImageRecipe"
      Components:
        - ComponentArn: !GetAtt ComponentConfigureOS.Arn
        - ComponentArn: !GetAtt ComponentNextflowAdvanced.Arn
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "Nextflow_AdvancedImageRecipe"]]
        ResourceType: "RLCatalyst-Research-Gateway"

  PClusterImageRecipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Sub "${AWS::StackName}-PClusterImageRecipe"
      Version: !Ref Ver
      ParentImage: !Ref MasterAMI
      Description: !Sub "${AWS::StackName}-PClusterImageRecipe"
      Components:
        - ComponentArn: !GetAtt ComponentConfigureOS.Arn
        - ComponentArn: !GetAtt ComponentPCluster.Arn
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "PClusterImageRecipe"]]
        ResourceType: "RLCatalyst-Research-Gateway"      

  ###############
  # INFRA CONFIG
  ###############
  NextflowAdvancedInfraConfig:
    Type: "AWS::ImageBuilder::InfrastructureConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-NextflowAdvanced-InfraConfig"
      InstanceProfileName: !Ref ResearchGatewayImgBldrInstancePfl
      InstanceTypes:
        - "m5.large"
      TerminateInstanceOnFailure: True
      SecurityGroupIds:
        - !Ref ResearchGatewayImgBldrInstanceSG
      SubnetId: !Ref PrivateSubnetId
      Logging:
        S3Logs:
          S3BucketName: !Ref SourceBucketName
          S3KeyPrefix:
            !Join ["/", ["Logs", "RL_RG_Nextflow_Advanced", !Ref Ver]]
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "NextflowAdvancedInfraConfig"]]
        ResourceType: "RLCatalyst-Research-Gateway"

  RStudioInfraConfig:
    Type: "AWS::ImageBuilder::InfrastructureConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-RStudio-InfraConfig"
      InstanceProfileName: !Ref ResearchGatewayImgBldrInstancePfl
      InstanceTypes:
        - "m5.large"
      TerminateInstanceOnFailure: True
      SecurityGroupIds:
        - !Ref ResearchGatewayImgBldrInstanceSG
      SubnetId: !Ref PrivateSubnetId
      Logging:
        S3Logs:
          S3BucketName: !Ref SourceBucketName
          S3KeyPrefix: !Join ["/", ["Logs", "RL_RG_RStudio", !Ref Ver]]
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "RStudioInfraConfig"]]
        ResourceType: "RLCatalyst-Research-Gateway"

  PClusterInfraConfig:
    Type: "AWS::ImageBuilder::InfrastructureConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-PCluster-InfraConfig"
      InstanceProfileName: !Ref ResearchGatewayImgBldrInstancePfl
      InstanceTypes:
        - "m5.large"
      TerminateInstanceOnFailure: True
      SecurityGroupIds:
        - !Ref ResearchGatewayImgBldrInstanceSG
      SubnetId: !Ref PrivateSubnetId
      Logging:
        S3Logs:
          S3BucketName: !Ref SourceBucketName
          S3KeyPrefix: !Join ["/", ["Logs", "RL_RG_PCluster", !Ref Ver]]
      Tags:
        Name: !Join ["-", [!Ref AWS::StackName, "PClusterInfraConfig"]]
        ResourceType: "RLCatalyst-Research-Gateway"      

  ResearchGatewayImgBldrInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP from the load balancer only
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value:
            !Join ["-", [!Ref AWS::StackName, "BuildAMIInstanceSecurityGroup"]]
        - Key: ResourceType
          Value: "RLCatalyst-Research-Gateway"

  ResearchGatewayImgBldrInstancePfl:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref ResearchGatewayInstanceRole

  ResearchGatewayInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action:
              - sts:AssumeRole
      Path: /

  ###############
  # DISTRIBUTION
  ###############
  NextflowAdvancedDistributionConfiguration:
    Type: "AWS::ImageBuilder::DistributionConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-Nextflow_Advanced-DistributionConfig"
      Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
      Distributions:
        - Region: "us-east-2"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "us-east-1"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "us-west-2"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "us-west-1"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "ap-south-1"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "ap-southeast-1"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
        - Region: "ap-southeast-2"
          AmiDistributionConfiguration:
            Name: "Nextflow_Advanced {{ imagebuilder:buildDate }}"
            Description: "Nextflow_Advanced for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "Nextflow_Advanced"
      Tags:
        RLCatalyst-Product: "Nextflow_Advanced"
  RStudioDistributionConfiguration:
    Type: "AWS::ImageBuilder::DistributionConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-RStudioDistributionConfig"
      Description: "RStudio for RLCatalyst Research Gateway"
      Distributions:
        - Region: "us-east-2"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "us-east-1"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "us-west-2"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "us-west-1"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "ap-south-1"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "ap-southeast-1"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
        - Region: "ap-southeast-2"
          AmiDistributionConfiguration:
            Name: "RStudio {{ imagebuilder:buildDate }}"
            Description: "RStudio for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "RStudio"
      Tags:
        Name: "RStudio"
        RLCatalystProduct: "RStudio"
  PClusterDistributionConfiguration:
    Type: "AWS::ImageBuilder::DistributionConfiguration"
    Properties:
      Name: !Sub "${AWS::StackName}-PClusterDistributionConfig"
      Description: "PCluster for RLCatalyst Research Gateway"
      Distributions:
        - Region: "us-east-2"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "us-east-1"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "us-west-2"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "us-west-1"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "ap-south-1"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "ap-southeast-1"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
        - Region: "ap-southeast-2"
          AmiDistributionConfiguration:
            Name: "PCluster {{ imagebuilder:buildDate }}"
            Description: "PCluster for RLCatalyst Research Gateway"
            AmiTags:
              RLCatalystProduct: "PCluster"
      Tags:
        Name: "PCluster"
        RLCatalystProduct: "PCluster"      

  ##############
  # PIPELINE
  ##############
  NextflowAdvancedImagePipeline:
    Type: "AWS::ImageBuilder::ImagePipeline"
    Properties:
      Name: !Sub "${AWS::StackName}-Pipeline_Nextflow_Advanced"
      Description: "Pipeline to build Nextflow_Advanced AMI for RLCatalyst Research Gateway"
      ImageRecipeArn: !Ref NextflowAdvancedImageRecipe
      InfrastructureConfigurationArn: !Ref NextflowAdvancedInfraConfig
      DistributionConfigurationArn: !Ref NextflowAdvancedDistributionConfiguration
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 90
      Status: "ENABLED"
      Tags:
        Name: "RL_RG_Nextflow_Advanced"
        ResourceType: "RLCatalyst-Research-Gateway"
  RStudioImagePipeline:
    Type: "AWS::ImageBuilder::ImagePipeline"
    Properties:
      Name: !Sub "${AWS::StackName}-Pipeline_RStudio"
      Description: "Pipeline to build RStudio AMI for RLCatalyst Research Gateway"
      ImageRecipeArn: !Ref RStudioImageRecipe
      InfrastructureConfigurationArn: !Ref RStudioInfraConfig
      DistributionConfigurationArn: !Ref RStudioDistributionConfiguration
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 90
      Status: "ENABLED"
      Tags:
        Name: "RL_RG_RStudio"
        ResourceType: "RLCatalyst-Research-Gateway"

  PClusterImagePipeline:
    Type: "AWS::ImageBuilder::ImagePipeline"
    Properties:
      Name: !Sub "${AWS::StackName}-Pipeline_PCluster"
      Description: "Pipeline to build PCluster AMI for RLCatalyst Research Gateway"
      ImageRecipeArn: !Ref PClusterImageRecipe
      InfrastructureConfigurationArn: !Ref PClusterInfraConfig
      DistributionConfigurationArn: !Ref PClusterDistributionConfiguration
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 90
      Status: "ENABLED"
      Tags:
        Name: "RL_RG_PCluster"
        ResourceType: "RLCatalyst-Research-Gateway"      

Outputs:
  NextflowAdvancedImagePipeline:
    Description: Nextflow_Advanced Image Builder Pipeline
    Value: !Ref NextflowAdvancedImagePipeline
    Export:
      Name: !Sub "${AWS::StackName}-NextflowAdvancedImagePipeline"
  RStudioImagePipeline:
    Description: RStudio Image Builder Pipeline
    Value: !Ref RStudioImagePipeline
    Export:
      Name: !Sub "${AWS::StackName}-RStudioPipelineName"
  PClusterImagePipeline:
    Description: PCluster Image Builder Pipeline
    Value: !Ref PClusterImagePipeline
    Export:
      Name: !Sub "${AWS::StackName}-PClusterPipelineName"